
version: "3"
services:
  emily-dm_waldo_server-rdo7sd:

    # Add your custom configuration here!
    expose:
      - 4242
    ports:
      - "4242:4242"

    networks:
      - emily-dm_waldo_server-rdo7sd-network
